[application]

# App (Project) Name
name = "peering-rotko-net"

[bundle]
identifier = "net.rotko.peering"
publisher = "Rotko Peering"

[web.app]

# HTML title tag content
title = "Peering - Rotko Networks"

# include `resources` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
