name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan peering.rotko.net >> ~/.ssh/known_hosts

      - name: Sync files to server
        run: |
          rsync -avz --delete ./ peering@peering.rotko.net:/home/peering/peering.rotko.net

      - name: Restart Docker Compose
        run: |
          ssh peering@peering.rotko.net "cd /home/peering/peering.rotko.net && docker-compose up -d --build"
